from sqlalchemy import (
    BigInteger, Boolean, Column, String, Index, Integer, Date, DateTime,
    Text
)
from base_sqlalchemy import Base
import datetime


# Swachh Manch user model
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    username = Column(String(50),)
    email = Column(String(255))
    password = Column(String(255))
    mobile_number = Column(String(20), index=True)
    otp = Column(String(80))
    otp_sent_at = Column(DateTime)
    mobile_number_verified = Column(Boolean, default=False)
    mobile_number_verified_at = Column(DateTime)
    email_activation_token = Column(String(255))
    email_activation_token_sent_at = Column(DateTime)
    email_verified = Column(Boolean, default=False)
    email_verified_at = Column(DateTime)
    remember_token = Column(String(100))
    mac_address = Column(String(255))
    banned = Column(Boolean, default=False, index=True)
    banned_at = Column(DateTime)
    last_login_at = Column(DateTime)
    last_login_ip = Column(String(30))
    last_login_user_agent = Column(String(255))
    created_at = Column(DateTime, default=datetime.datetime.now)
    updated_at = Column(DateTime, onupdate=datetime.datetime.now)
    deleted = Column(Boolean, default=False, index=True)
    deleted_at = Column(DateTime)
    non_verified_mobile_number = Column(String(20))
    non_verified_mobile_number_otp = Column(String(80))
    non_verified_mobile_number_otp_sent_at = Column(DateTime)
    otp_source = Column(String(50), default="mvaayoo")
    login_token = Column(String(100))
    login_token_sent_at = Column(DateTime)
    migrated_at = Column(DateTime)
    icmyc_user_id = Column(BigInteger, index=True)

    
Index('users_mobile_number_email_deleted_unique', User.mobile_number, User.email, User.deleted)
Index('users_mobile_number_deleted_unique', User.mobile_number, User.deleted)
Index('users_email_deleted_unique', User.email, User.deleted)


# ICMYC user model
class IcmycUser(Base):
    __tablename__ = 'icmyc_users'

    id = Column(Integer, primary_key=True)
    role_id = Column(Integer, default=1, index=True)
    swachh_manch_user_id = Column(Integer, index=True)
    full_name = Column(String(191))
    email = Column(String(255), index=True)
    password = Column(String(255))
    mobile_number = Column(String(20), index=True)
    description = Column(Text())
    city_id = Column(Integer)
    city_title = Column(String(191))
    ward_id = Column(Integer)
    ward_title = Column(String(191))
    location = Column(String(191))
    address = Column(String(191))
    postal_code = Column(String(25))
    birthday = Column(Date)
    gender = Column(String(1))
    latitude = Column(String(30))
    longitude = Column(String(30))
    otp = Column(String(80))
    otp_sent_at = Column(DateTime)
    otp_verified = Column(Boolean, default=False)
    otp_verified_at = Column(DateTime)
    otp_verified_page_uri = Column(String(1000))
    activation_code = Column(String(191))
    activation_code_sent_at = Column(DateTime)
    email_verified = Column(Boolean, default=False)
    email_verified_at = Column(DateTime)
    welcome_page_visited_at = Column(DateTime)
    near_complaints_page_visited_at = Column(DateTime)
    invite_friends_page_visited_at = Column(DateTime)
    dashboard_page_visited_at = Column(DateTime)
    preffered_annoying_category_id = Column(Integer)
    last_login_at = Column(DateTime)
    last_user_id = Column(Integer)
    dashboard_banner_status = Column(Integer)
    neighbourhoods_banner_status = Column(Integer)
    pages_banner_status = Column(Integer)
    sign_up_ip = Column(String(40))
    sign_up_user_agent = Column(String(191))
    sign_up_channel_id = Column(Integer)
    sign_in_ip = Column(String(40))
    sign_in_user_agent = Column(String(191))
    sign_in_channel_id = Column(Integer)
    device_token = Column(String(191))
    mac_address = Column(String(191))
    refferer_user_id = Column(Integer)
    session_count = Column(Integer)
    age_for_pb = Column(String(100))
    signed_up_with = Column(String(100))
    status = Column(Boolean, default=True)
    activated = Column(Boolean, default=False)
    avatar = Column(String(255))
    avatar_id = Column(Integer)
    slug = Column(String(255), index=True)
    social_user = Column(Boolean, default=False)
    failed_login_count = Column(Integer)
    remember_token = Column(String(100))
    logged_in = Column(Boolean, default=False)
    logged_out_at = Column(DateTime)
    posted_complaint_count = Column(Integer)
    voteup_count = Column(Integer)
    shared_complaint_count = Column(Integer)
    following_count = Column(Integer)
    follower_count = Column(Integer)
    email_notify_enabled = Column(Boolean, default=True)
    push_notifications_enabled = Column(Boolean, default=True)
    last_activity_at = Column(DateTime)
    bounce_status = Column(Integer)
    created_at = Column(DateTime, default=datetime.datetime.now)
    updated_at = Column(DateTime, onupdate=datetime.datetime.now)
    deleted_at = Column(DateTime)

Index('users_mobile_number_status_unique', IcmycUser.mobile_number, IcmycUser.status)
Index('users_email_status_unique', IcmycUser.email, IcmycUser.status)